# Generated by Django 4.2 on 2025-07-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id_agente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('tramite', 'Trámite iniciado')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto'), ('redireccionado', 'Redireccionado')], default='pendiente', max_length=20)),
                ('referencia_tramite', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones_usuario', models.TextField(blank=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.agente')),
            ],
        ),
        migrations.CreateModel(
            name='DependenciaLaboral',
            fields=[
                ('id_dependencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('tel_contacto', models.CharField(max_length=30)),
                ('activa_dependencia', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dependencia Laboral',
                'verbose_name_plural': 'Dependencias Laborales',
                'db_table': 'dependencia_laboral',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=128)),
                ('activo_usuario', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chatbot_app.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tema', models.CharField(max_length=150)),
                ('es_redireccion_externa', models.BooleanField(default=False)),
                ('detalle_respuesta', models.TextField(blank=True, null=True)),
                ('contacto_externo', models.CharField(blank=True, max_length=150, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo_tema', models.BooleanField(default=True)),
                ('tema_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtemas', to='chatbot_app.tema')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialInteraccion',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje_agente', models.TextField(blank=True, null=True)),
                ('respuesta_sistema', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='chatbot_app.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_app.tema'),
        ),
        migrations.AddField(
            model_name='agente',
            name='dependencia_laboral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_app.dependencialaboral'),
        ),
        migrations.AddConstraint(
            model_name='tema',
            constraint=models.UniqueConstraint(fields=('nombre_tema', 'tema_padre'), name='unique_nombre_por_padre'),
        ),
    ]
