# Generated by Django 4.2 on 2025-07-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='contacto_externo',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='es_redireccion_externa',
        ),
    ]
