# Generated by Django 4.2 on 2025-08-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_remove_tema_contacto_externo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='referencia_informada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tema',
            name='requiere_referencia',
            field=models.BooleanField(default=False),
        ),
    ]
