# Generated by Django 4.2 on 2025-08-31 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0003_consulta_referencia_informada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.RenameField(
            model_name='historialinteraccion',
            old_name='mensaje_agente',
            new_name='mensaje_cliente',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='agente',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='referencia_informada',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='referencia_tramite',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Agente',
        ),
        migrations.DeleteModel(
            name='DependenciaLaboral',
        ),
        migrations.AddField(
            model_name='consulta',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.cliente'),
            preserve_default=False,
        ),
    ]
