# Generated by Django 4.2 on 2025-08-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0004_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='requiere_referencia',
        ),
    ]
